#!/bin/bash
# imagemagick ufraw-batch
#VAR

IMG_RESOLUTION="900x"


DIRIN=$1
DIROUT=$2
PROJET=$3

rm -rf $DIROUT/$PROJET
mkdir $DIROUT/$PROJET
OUT=$DIROUT/$PROJET/index.html

exe_dirlist $DIRIN $DIROUT/$PROJET/ $IMG_RESOLUTION


zip -r $DIROUT/$PROJET.zip $DIROUT/$PROJET


echo "---END---"

