#!/bin/bash
# imagemagick ufraw-batch
#VAR

DIRIN=$1
DIROUT=$2
PROJET=$3

rm -rf $DIROUT/$PROJET
mkdir $DIROUT/$PROJET
OUT=$DIROUT/$PROJET/index.html

size=`du -sh $DIRIN`
tot=`echo $size | cut -d' ' -f1`
echo " DIRECTORY SIZE = $tot <br><br>" >> $OUT

exe_dirlist $DIRIN $DIROUT/$PROJET/ 


zip -r $DIROUT/$PROJET.zip $DIROUT/$PROJET


echo "---END---"

