#!/bin/bash

#VAR
DIRIN=$1
DIROUT=$2
GRESO="600x"




mkdir $DIROUT 
OUT=$DIROUT/index.html > /dev/null


echo "<fieldset><legend>SIZE</legend>" >> $OUT

size=`du -sh $DIRIN`
tot=`echo $size | cut -d' ' -f1`
echo " DIRECTORY SIZE = $tot <br><br>" >> $OUT

echo "</fieldset>" >> $OUT


echo "<fieldset><legend>DIRECTORY</legend>" >> $OUT

cd $DIRIN
for DIR in $(ls -d */)
do
    size=`du -sh $DIRIN$DIR`
    tot=`echo $size | cut -d' ' -f1`
    
	
	echo  "<a href=\"$DIR\">[ $tot ] : $DIR : </a><br>" >> $OUT
	mkdir $DIROUT/$name/$DIR > /dev/null
	exe_dirlist $DIRIN/$DIR $DIROUT/$DIR 
done
echo "</fieldset>" >> $OUT

echo "<br><br>" >> $OUT




echo "<fieldset><legend>IMAGES</legend>" >> $OUT

for FILE in $(ls -p $DIRIN | grep -v /);
do
	img=${FILE##*.}
	if [ $img = jpg ] || [ $img = JPG ] || [ $img = png ] || [ $img = PNG ] 
	then
        echo "RESIZE IMG $FILE"
        cp $FILE $DIROUT > /dev/null
		mogrify -resize $GRESO $DIROUT$FILE
		echo "<a href='$FILE'><img src='$FILE' height='300'></a>" >> $OUT
    fi

done
echo "</fieldset>" >> $OUT

echo "<br><br>" >> $OUT


echo "<fieldset><legend>RAW IMAGES</legend>" >> $OUT

for FILE in $(ls -p $DIRIN | grep -v /);
do
    name=${FILE%.*}
	ext=${FILE##*.}
	if [ $ext = cr2 ] || [ $ext = CR2 ] 
	then
        echo "RAW IMG $FILE"
        cp $FILE $DIROUT$FILE.cr2 > /dev/null
        ufraw-batch --out-type jpg $DIROUT$FILE.cr2
		mogrify -resize $GRESO $DIROUT$name.cr2.jpg
        rm $DIROUT$FILE.cr2 > /dev/null
		echo "<a href='$name.cr2.jpg'><img src='$name.cr2.jpg' height='300'></a>" >> $OUT
    fi

done
echo "</fieldset>" >> $OUT
echo "<br><br>" >> $OUT


echo "<fieldset><legend>FILE</legend>" >> $OUT

for FILE in $(ls -p $DIRIN | grep -v /);
do
	echo $FILE
    size=`du -sh $DIRIN$FILE`
    tot=`echo $size | cut -d' ' -f1`
    
	echo "[ $tot ] : "$FILE" <br>" >> $OUT

done

echo "</fieldset>" >> $OUT

